---
- name: Install nginx
  apt:
    name:
      - nginx
    state: latest
    update_cache: yes

- name: Copy configs
  copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/{{ item.dest }}"
    mode: 0644
    owner: root
  with_items:
    - {src: "default", dest: "sites-available/default"}
  notify: "reload nginx"

