[package]
name = "database"
version = "0.1.0"
authors = ["unknown"]

[dependencies]
ws = "*"
iron = "0.4"
router = "0.4"
rustc-serialize = "0.3"
chrono = { version = "0.2", features = ["rustc-serialize"] }
chashmap = "*"
time = "*"
base32 = "*"
log = "*"
simplelog = "*"