---
- name: Install prerequisites for docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: yes

- name:    Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name:    Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install Docker and NTP server
  apt:
    name:
     - docker-ce
     - ntp
    state: latest
    update_cache: yes

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: true
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create user
  user:
    name: vch
    createhome: yes
    system: yes
    shell: /usr/sbin/nologin

- name: Ensure perm 0750 on home
  file: path=/home/vch mode='0750'

- name: Copy sources
  copy:
    src: '../services/Vch/{{ item }}'
    dest: /home/vch/
    owner: vch
    group: vch
    mode: u=rwX,g=,o=
  with_items:
    - 'NTPTools'
    - 'VchAPI'
    - 'Vch.Core'
    - 'docker-compose.yml'
  notify: restart vch service

- name: Build service in docker
  shell: docker-compose run vch dotnet build -c Release
  args:
    chdir: /home/vch/

- name: Install systemd units
  copy:
    src: '{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
  notify: restart vch service
  with_items:
    - vch.service

- name: Enable services
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: restarted
    daemon_reload: yes
  with_items:
    - vch

