---
- name: Install dependencies (Go, postgres, redis)
  apt:
    name:
     - golang
     - postgresql
     - redis
    state: latest
    update_cache: yes

- name: Create user
  user:
    name: laberator
    createhome: yes
    system: yes
    groups: redis
    append: yes
    shell: /usr/sbin/nologin

- name: Configure postgres
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/10/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: u=rw,g=r,o=r

- name: Configure redis
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: u=rw,g=r,o=

- name: restart postgre and redis
  systemd:
    name: '{{ item }}'
    state: restarted
    daemon_reload: yes
  with_items:
    - postgresql@10-main
    - redis

- name: Provision postgres
  become_user: postgres
  shell: '{{ item }}'
  with_items:
    - createuser laberator || true
    - (psql --list  | grep laberator) || createdb --owner=laberator laberator

- name: chmod home
  file: dest=/home/laberator mode='o='

- name: Install laberator service
  copy:
    src: ../services/laberator/
    dest: /home/laberator/
    owner: laberator
    group: laberator
    mode: u=rwX,g=,o=
  notify: restart laberator service

- name: Chmod run.sh
  file: dest=/home/laberator/run.sh mode=u+x

- name: Create directory for fast-hash library
  file:
    path: /home/laberator/go/src/github.com/werelaxe/fast-hash
    state: directory
    owner: laberator
    group: laberator
    mode: u+rwX,g=,o=

- name: Install laberator fast-hash library
  copy:
    src: ../services/laberator-fast-hash/
    dest: /home/laberator/go/src/github.com/werelaxe/fast-hash/
    owner: laberator
    group: laberator
    mode: u+rwX,g=,o=
  notify: restart laberator service

- name: Download and install Go dependencies
  become_user: laberator
  shell: |
      go get -d
      cd go/src
      for pkg in github.com/*/*; do
          go get $pkg;
      done
  args:
    chdir: /home/laberator/

  #- name: Install postgres and redis systemd service
  #copy: src=postgresql@.service dest=/etc/systemd/system/postgresql@.service

- name: Install laberator systemd service
  copy: src=laberator.service dest=/etc/systemd/system/laberator.service
  notify: restart laberator service

- name: Enable laberator service
  systemd:
    name: laberator
    enabled: yes
    state: started
    daemon_reload: yes
