---
- name: Install dependencies (Go, postgres, redis)
  apt:
    name:
     - golang
     - postgresql
     - redis
    state: latest
    update_cache: yes

- name: Provision postgres  
  become_user: postgres
  shell: '{{ item }}'
  with_items:
    - psql -c "ALTER USER postgres PASSWORD 'nicepassword'"
    - (psql --list  | grep laberator) || createdb laberator

- name: Create user
  user:
    name: laberator
    createhome: yes
    system: yes
    shell: /usr/sbin/nologin

- name: Install laberator service
  copy:
    src: ../services/laberator/
    dest: /home/laberator/
    owner: laberator
    group: laberator
    mode: u=rwx,g=,o=
  notify: restart laberator service

- name: Create directory for fast-hash library
  file:
    path: /home/laberator/go/src/github.com/werelaxe/fast-hash
    state: directory
    owner: laberator
    group: laberator
    mode: u=rwx,g=,o=

- name: Install laberator fast-hash library
  copy:
    src: ../services/laberator-fast-hash/
    dest: /home/laberator/go/src/github.com/werelaxe/fast-hash/
    owner: laberator
    group: laberator
    mode: u=rwx,g=,o=
  notify: restart laberator service

- name: Download and install Go dependencies
  become_user: laberator
  shell: |
      go get -d
      cd go/src
      for pkg in github.com/*/*; do
          go get $pkg;
      done
  args:
    chdir: /home/laberator/

- name: Install laberator systemd service
  copy: src=laberator.service dest=/etc/systemd/system/laberator.service
  notify: restart laberator service

- name: Enable laberator service
  systemd:
    name: laberator
    enabled: yes
    state: started
    daemon_reload: yes
