- name: increase MaxStartups in sshd_config
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^MaxStartups "
    line: MaxStartups 100:30:600
    insertafter: "^#MaxStartups"
  notify: restart sshd

- name: increase the number of sessions in sshd_config
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^MaxSessions "
    line: MaxSessions 1000
    insertafter: "^MaxStartups"
  notify: restart sshd

- name: create cloud user
  user: name=cloud shell=/bin/bash

- name: add keys to cloud user
  authorized_key: user=cloud key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDY1Exi0TwlJezDkeD0A5iYHNjN4sGwWzveBU8KNhUwwG8UGTF/eB92QOEEL5RzUS7NMNd+xzs/AOExH2bNwh2OW+iKUpMF2kbatwj8uHsL+I09EA93b3c3i1yPouwvXbIlezWru1xpxyiWwGtgOl3SHh0lkfZWhqJ4IB1GCCmrF0ZzNPWRgiKZnjMJq7ggmHLrgjtoZfkFCg50Lxn9iIwJ+0k5LDeib3vsyCbvmrN3Jsy07/hIq7Ipou1mXQjc6ZgD5P8EzBaFeajnDexIk7oj6yqqJeyCAfxuMtzYgEPr2M+1fC36vhsMqY1ApMZP5Gt5I7sIy1SqwjjouNR/Vlht bay@baysnotebook"

- name: copy sudo_cloud
  copy: src=sudo_cloud dest=/etc/sudoers.d/ mode=0640

- name: copy virtualbox.list
  copy: src=virtualbox.list dest=/etc/apt/sources.list.d/

- name: add virtualbox repo keys
  apt_key:
    url: "{{item}}"
    state: present
  with_items:
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - https://www.virtualbox.org/download/oracle_vbox.asc

- name: apt update
  apt:
    update_cache: yes

- name: install virtualbox
  apt: name=virtualbox-5.2 state=latest

- name: load some modules
  modprobe:
    name: "{{item}}"
    state: present
  with_items:
    - vboxpci
    - vboxnetadp
    - vboxnetflt
    - vboxdrv

- name: copy cloud scripts
  copy: src=scripts dest=/cloud/ mode=755

- name: install openvpn
  apt: name=openvpn state=latest

- name: copy openvpn bridging script
  copy: src=add_to_team_bridge.sh dest=/etc/openvpn/ mode=755


