---
- name: Install utils
  apt:
    name:
      - apt-transport-https
      - mc
      - htop
      - rsync
    state: latest
    update_cache: yes

- name: Make directory for cloud-init
  file:
    path: /etc/cloud-init/
    state: directory
    mode: 0755
    owner: root

- name: Install cloud-init
  copy:
    src: "{{ item.src }}"
    dest: "{{  item.dest }}"
    mode: 0755
    owner: root
  with_items:
    - {src: "cloud-init.sh", dest: "/etc/cloud-init/cloud-init.sh"}
    - {src: "cloud-init.service", dest: "/etc/systemd/system/cloud-init.service"}

- name: Enable cloud-init
  systemd:
    name: cloud-init
    enabled: yes
    daemon_reload: yes

- name: Remove Ubuntu MOTD
  file: path='/etc/update-motd.d/{{ item }}' state=absent
  with_items:
    - 50-motd-news
    - 80-esm
    - 80-livepatch
    - 90-updates-available
    - 91-release-upgrade
    - 95-hwe-eol

- name: Copy MOTD
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: root
  with_items:
    - {src: "00-header", dest: "/etc/update-motd.d/00-header"}
    - {src: "10-help-text", dest: "/etc/update-motd.d/10-help-text"}

