- hosts: cs-checker, cs-master
  tasks:

  - name: sync catalog
    synchronize: src="../checkers" dest="{{cs_dir}}"

  - name: checker owner
    file:
      path:  "{{cs_dir}}/checkers"
      owner: "{{cs_user}}"
      group: "{{cs_user}}"
      recurse: yes

  - name: Install dotnet repo keys
    apt:
      deb: https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

  - name: Install .NET Core 2.1
    apt:
      name:
       - dotnet-sdk-2.1
      state: latest
      update_cache: yes

  - name: install sys deps
    apt: name=python3-pip state=latest

  - name: python deps
    pip: name={{item}} executable=pip3
    with_items:
      - requests
      - ws4py
      - beautifulsoup4
      - aiohttp
      - scipy
      - numpy
      - websocket-client

